#!/usr/bin/env python3
"""Render the schema.org JSON-LD block of site/index.html (c105).

Why this file exists
--------------------
site/index.html is hand-maintained, and the c98/c104 learnings are blunt about
what happens to hand-typed claim surfaces: they drift. The JSON-LD block makes
COUNTED claims (how many marks, which dates, what price), so it must be
rendered from the same sources everything else is rendered from, on every
publish, or it will quietly go false.

What it adds over the old hand-written block
--------------------------------------------
The old block declared only a WebApplication. That describes the free checker
but tells Google nothing about the thing that is actually discoverable: a
free, weekly-refreshed, public-domain DATASET. schema.org/Dataset is what
Google Dataset Search (datasetsearch.research.google.com) indexes, and it is
the one organic channel this venture can win without a human pitching anyone
(warn-feed already ships Dataset markup; tm-watch did not). We also declare
the paid watch as a Product/Offer so the $29 price is machine-readable and
cannot disagree with pricing.py.

Everything asserted here is checked by --selftest against the live artifacts:
row count and date range from marks.jsonl, issue count from fetched_issues.json,
price from pricing.py, and each declared distribution URL must exist on disk.

Usage:  python3 gen_jsonld.py [--out site] [--selftest]
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import pricing  # noqa: E402

SITE = "https://apventureengine.github.io/trademark-watch/"
REPO = "https://github.com/APVentureEngine/trademark-watch"
RAW = "https://raw.githubusercontent.com/APVentureEngine/trademark-watch/main/"
HF = "https://huggingface.co/datasets/APProjects/uspto-trademark-gazette-word-marks"
GUM_PAID = "https://approj.gumroad.com/l/pwvfma"
BEGIN = "<!--JSONLD:BEGIN generated by gen_jsonld.py — do not hand-edit-->"
END = "<!--JSONLD:END-->"


def facts(marks_path=None, issues_path=None):
    """Counted facts from the real artifacts. Never estimated."""
    marks_path = marks_path or os.path.join(HERE, "marks.jsonl")
    issues_path = issues_path or os.path.join(HERE, "fetched_issues.json")
    rows = 0
    lo = hi = None
    with open(marks_path) as f:
        for line in f:
            if not line.strip():
                continue
            d = json.loads(line)
            rows += 1
            p = d.get("pub_date") or d.get("transaction_date")
            if p:
                lo = p if lo is None or p < lo else lo
                hi = p if hi is None or p > hi else hi
    issues = sorted(k for k, v in json.load(open(issues_path)).items() if v)
    return {"rows": rows, "first": lo, "last": hi, "issues": len(issues),
            "issue_dates": issues}


def graph(f):
    """The @graph. Every number in here came from facts()/pricing.py."""
    org = {
        "@type": "Organization",
        "@id": SITE + "#operator",
        "name": "APProjects",
        "url": SITE,
        "sameAs": [REPO, HF],
    }
    dataset = {
        "@type": "Dataset",
        "@id": SITE + "#dataset",
        "name": "US trademark Official Gazette word marks, weekly",
        "alternateName": "USPTO Gazette word-mark index (published for opposition + registered)",
        "description": (
            "Every word mark in the US Trademark Official Gazette — applications "
            "published for opposition and registrations issued — normalized to one "
            "row per mark with serial, mark text, owner of record, filing date, "
            "publication date, event and international classes. %s marks from %s "
            "issues covering %s to %s. Rebuilt every Tuesday when the USPTO "
            "publishes a new issue; per-issue CSV files are immutable once written. "
            "Source data is US federal public domain."
            % (format(f["rows"], ","), f["issues"], f["first"], f["last"])
        ),
        "url": SITE + "data/",
        "sameAs": [HF, REPO],
        "creator": {"@id": SITE + "#operator"},
        "publisher": {"@id": SITE + "#operator"},
        "isAccessibleForFree": True,
        "license": "https://www.usa.gov/government-works",
        "temporalCoverage": "%s/%s" % (f["first"], f["last"]),
        "spatialCoverage": {"@type": "Place", "name": "United States"},
        "dateModified": f["last"],
        "keywords": ["trademark", "USPTO", "Official Gazette", "published for opposition",
                     "trademark registration", "intellectual property", "public domain data"],
        "variableMeasured": ["serial", "mark", "owner", "filing_date", "pub_date",
                             "event", "classes"],
        "isBasedOn": "https://www.uspto.gov/learning-and-resources/official-gazette",
        "distribution": [
            {"@type": "DataDownload", "name": "Latest Gazette issue (CSV)",
             "encodingFormat": "text/csv", "contentUrl": RAW + "data/latest.csv"},
            {"@type": "DataDownload", "name": "Issue manifest (JSON): every published issue file with row counts",
             "encodingFormat": "application/json", "contentUrl": RAW + "data/manifest.json"},
            {"@type": "DataDownload", "name": "Per-issue CSV archive",
             "encodingFormat": "text/csv", "contentUrl": SITE + "data/"},
            {"@type": "DataDownload", "name": "Full rolling index on Hugging Face",
             "encodingFormat": "text/csv", "contentUrl": HF},
        ],
    }
    app = {
        "@type": "WebApplication",
        "@id": SITE + "#checker",
        "name": "TM Watch — free trademark similarity search",
        "url": SITE,
        "applicationCategory": "BusinessApplication",
        "operatingSystem": "Web",
        "browserRequirements": "Requires JavaScript. Runs entirely client-side; nothing typed is transmitted.",
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
        "isBasedOn": {"@id": SITE + "#dataset"},
        "provider": {"@id": SITE + "#operator"},
        "description": (
            "Instant similarity report of a brand name against %s US trademark word "
            "marks published for opposition or registered between %s and %s (USPTO "
            "Official Gazette, a new issue every Tuesday). Runs in the browser: no "
            "account, no server, nothing typed is sent anywhere."
            % (format(f["rows"], ","), f["first"], f["last"])
        ),
    }
    product = {
        "@type": "Product",
        "@id": SITE + "#watch",
        "name": "TM Watch — automated weekly trademark watch (1 mark, 1 year)",
        "url": SITE,
        "brand": {"@id": SITE + "#operator"},
        "isBasedOn": {"@id": SITE + "#dataset"},
        "description": (
            "Every new USPTO Gazette issue is checked against your mark for 12 "
            "months; hits land on a private alert page and its RSS feed the day the "
            "issue publishes, while the 30-day opposition window is still open. "
            "One-time payment, nothing renews."
        ),
        "offers": {
            "@type": "Offer",
            "price": str(pricing.PRICE_USD),
            "priceCurrency": "USD",
            "url": GUM_PAID,
            "availability": "https://schema.org/InStock",
            "seller": {"@id": SITE + "#operator"},
        },
    }
    return {"@context": "https://schema.org", "@graph": [org, dataset, app, product]}


def block(f):
    body = json.dumps(graph(f), separators=(",", ":"), ensure_ascii=False)
    return '%s\n<script type="application/ld+json">\n%s\n</script>\n%s' % (BEGIN, body, END)


def render(out_dir):
    f = facts()
    path = os.path.join(HERE, out_dir, "index.html")
    html = open(path, encoding="utf-8").read()
    if BEGIN not in html or END not in html:
        raise SystemExit("gen_jsonld: markers missing in %s — add %s ... %s" % (path, BEGIN, END))
    pre, rest = html.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    new = pre + block(f) + post
    if new != html:
        open(path, "w", encoding="utf-8").write(new)
    print("gen_jsonld: %s marks, %s issues, %s..%s, price $%s -> %s"
          % (format(f["rows"], ","), f["issues"], f["first"], f["last"],
             pricing.PRICE_USD, path))


def selftest():
    f = facts()
    assert f["rows"] > 1000, f
    assert f["issues"] >= 4, f
    assert f["first"] and f["last"] and f["first"] <= f["last"], f
    g = graph(f)
    s = json.dumps(g)
    json.loads(s)  # must be valid JSON
    ids = [n["@type"] for n in g["@graph"]]
    assert ids == ["Organization", "Dataset", "WebApplication", "Product"], ids
    # price must equal pricing.py, never a literal
    assert g["@graph"][3]["offers"]["price"] == str(pricing.PRICE_USD)
    assert pricing.OLD_PRICE.lstrip("$") not in s, "stale price literal in JSON-LD"
    # counted claims must match the rendered prose sources
    assert format(f["rows"], ",") in g["@graph"][1]["description"]
    assert f["last"] in g["@graph"][1]["temporalCoverage"]
    # every on-disk distribution URL must actually exist in the built site
    site = os.path.join(HERE, "site")
    for rel in ("data/latest.csv", "data/manifest.json", "data/index.html"):
        p = os.path.join(site, rel)
        assert os.path.exists(p), "declared distribution missing on disk: " + p
    # no HTML-breaking sequence inside the script tag
    assert "</script" not in json.dumps(g)
    print("gen_jsonld selftest OK (%s marks, %s issues, $%s)"
          % (format(f["rows"], ","), f["issues"], pricing.PRICE_USD))


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        selftest()
    else:
        out = "site"
        if "--out" in sys.argv:
            out = sys.argv[sys.argv.index("--out") + 1]
        render(out)
