#!/usr/bin/env python3
"""Gumroad product ASSETS for TM Watch — cover image, attached file, buyer
content page — all driven from here with NO human in the loop.

TWIN FILE: ventures/warn-feed/product/gum_assets.py holds the same three
helpers (upload_file / replace_file / cover) plus warn-feed's copy sync. If
you fix a bug in one, fix it in the other; they are deliberately standalone so
either venture can die without breaking the other.

DISCOVERED c101 (2026-09-03). Gumroad is open source (github.com/antiwork/
gumroad) and app/controllers/api/v2/{files,covers}_controller.rb expose routes
the public docs never mention:
    POST /v2/files/presign  {filename,file_size}
        -> {upload_id, key, file_url, parts:[{part_number, presigned_url}]}
    PUT  <presigned_url>  (raw bytes, 100 MB parts) -> ETag header
    POST /v2/files/complete {upload_id,key,parts:[{part_number,etag}]} -> file_url
    PUT  /v2/products/:id   JSON body {"files":[{"url":...,"display_name":...}]}
    POST /v2/products/:id/covers {url:<public image URL>}  (server fetches it)
    DELETE /v2/products/:id/covers/:guid
Gotchas: (1) nested params MUST be a JSON body — form-encoded files[][url]
repeats do not pair into objects; (2) you cannot remove a file that a rich
content fileEmbed references unless the same request also sends replacement
rich_content, so replace in two calls (attach new alongside old, then send
files=[new] + rich_content=[embed of new]); (3) custom_fields sub-routes look
the field up by NAME, not id, and update only toggles `required`.

Usage (idempotent; the PDF/cover are regenerated by gen_covers.py first):
    ../../warn-feed/product/.venv/bin/python gen_covers.py   # PIL lives there
    python3 gum_assets.py sync            # cover + PDF + content page + receipt
    python3 gum_assets.py cover <pid> <public_image_url>
"""
import json, os, sys, urllib.error, urllib.parse, urllib.request, uuid
from pricing import PRICE_YEAR, PRICE_CENTS, PRICE, OLD_PRICE, EMAIL_ROUTE_TEXT

HERE = os.path.dirname(os.path.abspath(__file__))
API = "https://api.gumroad.com"
TOK = os.environ.get("GUMROAD_ACCESS_TOKEN", "")
PAID = "yqoJ16p67-UfQ1hnOtExvQ=="            # TM Watch — paid, 1 mark/year (price: pricing.py)
FREE = "DXbAI_1fRuKYAp8J7GUz0Q=="            # Free 30-day trademark watch
PAGES = "https://apventureengine.github.io/trademark-watch"
PDF = os.path.join(HERE, "..", "assets", "how-your-watch-works.pdf")
PDF_FREE = os.path.join(HERE, "..", "assets", "how-your-free-watch-works.pdf")
PART = 100 * 1024 * 1024

RECEIPT = (
    "Thank you. Your private alert page is being created and goes live within one refresh cycle "
    f"(at most 24h) at {PAGES}/alerts/ — open that link, type your mark exactly as you entered it "
    "and the email address you used for this purchase, and your page opens. Bookmark it; it also "
    "has an RSS feed if you would rather be pushed than pull. " + EMAIL_ROUTE_TEXT + " New matches appear after each Tuesday "
    "USPTO Official Gazette issue. The attached PDF repeats these steps. If you gave a GitHub "
    "username you also get a private-repo invite with the same alerts as files. Questions or a "
    "refund within 14 days: reply to this receipt."
)
RECEIPT_FREE = (
    "Thank you. Your free 30-day watch is being set up and your private alert page goes live within one "
    f"refresh cycle (at most 24h) at {PAGES}/alerts/ — open that link, type your mark exactly as you "
    "entered it and the email address you used here, and your page opens. Bookmark it; it has an RSS feed "
    "if you would rather be pushed than pull. " + EMAIL_ROUTE_TEXT + " New matches appear after each Tuesday USPTO Official "
    "Gazette issue. Nothing is charged, nothing renews: after 30 days the page shows an 'expired' banner "
    "and a link to keep watching for " + PRICE_YEAR + " if you want to. The attached PDF repeats these steps. "
    "Questions: reply to this receipt."
)
CONTENT_TEXT_FREE = (
    "Your free 30-day watch is running. The PDF above explains what we check and when. Your private alert "
    f"page: {PAGES}/alerts/ — open it with your mark text and the email you signed up with. RSS feed included."
)
CONTENT_TEXT = (
    "Your watch is running. The PDF above explains what we check and when. Your private alert page: "
    f"{PAGES}/alerts/ — open it with your mark text and your purchase email. It carries an RSS feed too."
)


def _open(req):
    try:
        with urllib.request.urlopen(req, timeout=300) as r:
            return r.status, dict(r.headers), r.read()
    except urllib.error.HTTPError as e:
        return e.code, dict(e.headers), e.read()


def api(method, path, form=None, jsonbody=None):
    url = API + path + ("?" if "?" not in path else "&") + "access_token=" + urllib.parse.quote(TOK)
    if jsonbody is not None:
        req = urllib.request.Request(url, data=json.dumps(jsonbody).encode(), method=method,
                                     headers={"Content-Type": "application/json"})
    else:
        req = urllib.request.Request(url, data=urllib.parse.urlencode(dict(form or {}), doseq=True).encode(),
                                     method=method)
    st, _, body = _open(req)
    try:
        return json.loads(body)
    except Exception:
        return {"success": False, "message": f"HTTP {st}: {body[:200]!r}"}


def get_product(pid):
    return api("GET", f"/v2/products/{urllib.parse.quote(pid, safe='')}").get("product") or {}


def upload_file(path):
    size = os.path.getsize(path)
    pre = api("POST", "/v2/files/presign", {"filename": os.path.basename(path), "file_size": size})
    if not pre.get("success"):
        raise SystemExit(f"presign failed: {pre}")
    parts = []
    with open(path, "rb") as fh:
        for p in pre["parts"]:
            st, hdrs, body = _open(urllib.request.Request(p["presigned_url"], data=fh.read(PART), method="PUT"))
            if st not in (200, 204):
                raise SystemExit(f"part {p['part_number']} PUT {st}: {body[:200]!r}")
            parts.append({"part_number": p["part_number"],
                          "etag": (hdrs.get("ETag") or hdrs.get("Etag") or "").strip('"')})
    done = api("POST", "/v2/files/complete",
               jsonbody={"upload_id": pre["upload_id"], "key": pre["key"], "parts": parts})
    if not done.get("success"):
        raise SystemExit(f"complete failed: {done}")
    return done["file_url"]


def replace_file(pid, path, display_name, body_text):
    p = get_product(pid)
    old_ids = [f["id"] for f in (p.get("files") or [])]
    page_id = (p.get("rich_content") or [{}])[0].get("id")
    url = upload_file(path)
    r = api("PUT", f"/v2/products/{urllib.parse.quote(pid, safe='')}",
            jsonbody={"files": [{"id": i} for i in old_ids] + [{"url": url, "display_name": display_name}]})
    if not r.get("success"):
        raise SystemExit(f"attach failed: {r}")
    new_id = [f["id"] for f in r["product"]["files"] if f["id"] not in old_ids][0]
    page = {"title": None, "description": {"type": "doc", "content": [
        {"type": "fileEmbed", "attrs": {"id": new_id, "uid": str(uuid.uuid4()), "collapsed": False}},
        {"type": "paragraph", "content": [{"type": "text", "text": body_text}]}]}}
    if page_id:
        page["id"] = page_id
    r2 = api("PUT", f"/v2/products/{urllib.parse.quote(pid, safe='')}",
             jsonbody={"files": [{"id": new_id}], "rich_content": [page]})
    if not r2.get("success"):
        raise SystemExit(f"swap failed: {r2}")
    back = get_product(pid)
    assert [f["id"] for f in back["files"]] == [new_id], "round-trip mismatch"
    return new_id


def set_cover(pid, image_url, replace=True):
    """Add a cover from a public URL; drop older ones so the listing shows the
    current artwork (covers are ordered, extras become a carousel)."""
    p = get_product(pid)
    old = [c.get("id") for c in (p.get("covers") or []) if c.get("id")]
    r = api("POST", f"/v2/products/{urllib.parse.quote(pid, safe='')}/covers", {"url": image_url})
    if not r.get("success"):
        raise SystemExit(f"cover failed: {r}")
    if replace:
        for guid in old:
            api("DELETE", f"/v2/products/{urllib.parse.quote(pid, safe='')}/covers/{guid}")
    return r


def main():
    if not TOK:
        raise SystemExit("GUMROAD_ACCESS_TOKEN missing")
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "sync":
        fid = replace_file(PAID, PDF, "TM Watch — how your watch works (setup + what to expect).pdf",
                           CONTENT_TEXT)
        print("paid file ->", fid)
        ffid = replace_file(FREE, PDF_FREE, "TM Watch — how your free 30-day watch works.pdf", CONTENT_TEXT_FREE)
        print("free file ->", ffid)
        rf = api("PUT", f"/v2/products/{urllib.parse.quote(FREE, safe='')}", {"custom_receipt": RECEIPT_FREE})
        assert rf.get("success"), rf
        assert get_product(FREE)["custom_receipt"] == RECEIPT_FREE, "free receipt round-trip mismatch"
        set_cover(PAID, f"{PAGES}/assets/cover.png")
        set_cover(FREE, f"{PAGES}/assets/cover-free.png")
        r = api("PUT", f"/v2/products/{urllib.parse.quote(PAID, safe='')}", {"custom_receipt": RECEIPT})
        assert r.get("success"), r
        back = get_product(PAID)
        assert back["custom_receipt"] == RECEIPT, "receipt round-trip mismatch"
        assert "access code" not in back["custom_receipt"]
        print("covers + receipt synced;",
              "paid covers:", len(back.get("covers") or []),
              "free covers:", len(get_product(FREE).get("covers") or []))
    elif cmd == "price-check":
        # c104: the listings are off-repo claim surfaces; assert they agree with pricing.py
        bad = []
        for pid, label in ((PAID, "paid"), (FREE, "free")):
            p = get_product(pid)
            text = (p.get("description") or "") + (p.get("custom_receipt") or "")
            if OLD_PRICE in text:
                bad.append("%s listing still says %s" % (label, OLD_PRICE))
            if label == "paid" and int(p.get("price") or 0) != PRICE_CENTS:
                bad.append("paid price is %s cents, pricing.py says %d" % (p.get("price"), PRICE_CENTS))
            if label == "paid" and PRICE not in (p.get("description") or ""):
                bad.append("paid description never states %s" % PRICE)
        for b in bad:
            print("GUMROAD PRICE MISMATCH: " + b)
        print("gumroad price-check: %d problem(s); price %s" % (len(bad), PRICE))
        sys.exit(1 if bad else 0)
    elif cmd == "cover":
        print(json.dumps(set_cover(sys.argv[2], sys.argv[3]))[:300])
    else:
        print(__doc__)


if __name__ == "__main__":
    main()
