#!/usr/bin/env node
/* TM Watch JS-port selftest — cross-implementation parity gate (INDEX_DESIGN
 * port checklist). Runs under Node (GitHub Actions; no local Node on the
 * founder VM). Exit 0 iff:
 *   1. PARITY: for every vector in parity-vectors.json (generated by
 *      gen_vectors.py from matcher.py ground truth), matcher.js produces the
 *      IDENTICAL flag, reason kinds (text before '('), phonetic codes, and
 *      normalized forms.
 *   2. GATE: recall >= 0.80 on expect=="yes" benchmark vectors (same binding
 *      launch gate as selftest.py), and FP count on negatives reported.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const M = require("./matcher.js");

const doc = JSON.parse(
  fs.readFileSync(path.join(__dirname, "parity-vectors.json"), "utf8"));

function kinds(reasons) { return reasons.map(r => r.split("(")[0]); }
function eqArr(a, b) {
  return a.length === b.length && a.every((x, i) => x === b[i]);
}

let mismatches = 0, mustFlag = 0, flaggedMust = 0, negTotal = 0, negFlagged = 0;

for (const v of doc.vectors) {
  const r = M.compare(v.m1, v.m2);
  const k = kinds(r.reasons);
  const ok = r.flag === v.flag && eqArr(k, v.kinds) &&
    r.detail.phon1 === v.phon1 && r.detail.phon2 === v.phon2 &&
    r.detail.norm1 === v.norm1 && r.detail.norm2 === v.norm2;
  if (!ok) {
    mismatches++;
    console.log(`PARITY-MISMATCH ${JSON.stringify(v.m1)} vs ${JSON.stringify(v.m2)}`);
    console.log(`  py: flag=${v.flag} kinds=${v.kinds} phon=${v.phon1}/${v.phon2} norm=${JSON.stringify(v.norm1)}/${JSON.stringify(v.norm2)}`);
    console.log(`  js: flag=${r.flag} kinds=${k} phon=${r.detail.phon1}/${r.detail.phon2} norm=${JSON.stringify(r.detail.norm1)}/${JSON.stringify(r.detail.norm2)}`);
  }
  if (v.expect === "yes") { mustFlag++; if (r.flag) flaggedMust++; }
  if (v.expect === "neg") { negTotal++; if (r.flag) negFlagged++; }
}

// direct metaphone parity
for (const p of doc.phonetic) {
  const code = M.metaphoneLite(M.normalize(p.s));
  if (code !== p.code) {
    mismatches++;
    console.log(`PHONETIC-MISMATCH ${JSON.stringify(p.s)}: py=${p.code} js=${code}`);
  }
}

const recall = mustFlag ? flaggedMust / mustFlag : 0;
console.log(`parity: ${doc.vectors.length} vectors, ${mismatches} mismatches`);
console.log(`gate: recall ${flaggedMust}/${mustFlag} = ${recall.toFixed(2)} (need >=0.80); negatives flagged ${negFlagged}/${negTotal}`);

if (mismatches > 0 || recall < 0.80) {
  console.log("SELFTEST FAIL");
  process.exit(1);
}
console.log("SELFTEST PASS");
